### ISSUE TITLE
Java Application using Tnt4J may not insert data into the target.

### ISSUE THREAD

**Issue by wookim007** [Nastel/TNT4J#10]
If java Applcation with "tnt4j.properties" like below values
"event.sink.factory: com.nastel.jkool.tnt4j.sink.BufferedEventSinkFactory" -- (It is a default value in JESL package), data may not be inserted into the target due to closing connection before handling data process.

**Comment by amavashev** [comment]
Added a FlushHook that gets invoked on VM shutdown. This hook forces a flush of all internal sink buffers before JVM shutdown to prevent loss of any buffered events. This feature is disabled by default, to enable it define java property: tnt4j.flush.on.vm.shutdown=true
