### ISSUE TITLE
DateTime properties are not in microsecond resolution

### ISSUE THREAD

**Issue by jbnas** [Nastel/TNT4J#26]
Currently, tracking event timestamps are reported in microsecond resolution, using UsecTimestamp class to maintain them.  However, for Properties, it uses java.util.Date objects to hold timestamp, which is only in millisecond resolution.

Property class should use UsecTimestamp instead of java.util.Date.  If property is created with a java.util.Date object, it should convert it to a UsecTimestamp.

**Comment by jbnas** [comment]
Also, when reporting data type of Property, it is not returning "date" for UsecTimestamp properties.  In `com.jkoolcloud.tnt4j.core.Property.getDataType()`:
```
  } else if (value instanceof Date) {
   return "date";
```
should be:
```
  } else if (value instanceof Date || value instanceof UsecTimestamp) {
   return "date";
```
or just:
```
  } else if (value instanceof UsecTimestamp) {
   return "date";
```
if recommended change above is done.

**Comment by amavashev** [comment]
Added support for UsecTimestamp using "date.usec" type.
} else if (value instanceof UsecTimestamp) {
   return "date.usec";
