### ISSUE TITLE
Potential error with child member hiding parent member

### ISSUE THREAD

**Issue by jbnas** [Nastel/TNT4J#27]
Have the following Eclipse warning:

`The field FileDumpSink.formatter is hiding a field from type FileSink in:		/tnt4j/src/main/java/com/jkoolcloud/tnt4j/dump/FileDumpSink.java	line 36
`

I would think that child class wants to use member defined in parent class.

To see these types of warnings, need to set the following Eclipse preference to not ignore it (I set it to Warning):

`Java=>Compiler=>Errors/Warnings: Name shadowing and conflicts=>Field declaration hides another field or variable`

Probably a good idea if everyone set this to Warning, since in most cases this is unintended behavior.

**Comment by kausandr** [comment]
field renamed to dumpFormatter
