### ISSUE TITLE
UsecTimestamp is no longer formatted correctly

### ISSUE THREAD

**Issue by jbnas** [Nastel/TNT4J#28]
It seems that the usec portion of time stamp is being printed twice, for example:

`2020-01-13 10:40:15.018593593 EST`

notice the usecs `593` is printed a second time

Noticed with `toString()` method.  Using `toString("yyyy-MM-dd HH:mm:ss.SSSSSS XXX")` works fine.

**Comment by jbnas** [comment]
Will need a release that includes this fix

**Comment by kausandr** [comment]
See https://github.com/Nastel/TNT4J/releases/tag/v2.12.2
