### ISSUE TITLE
UsecTimestamp converted to invalid timestamp string

### ISSUE THREAD

**Issue by evaldasguogis** [Nastel/TNT4J#32]
**Describe the bug**
When UsecTimestamp is converted to timestamp string and UTC timezone is used, timestamp is invalid.
The timezone part is 00:00, but it should have + or - sign according to specification.

**To Reproduce**
Run this code:
        UsecTimestamp ts = new UsecTimestamp(1652777518123L, 456);
        System.out.println(ts.toString("yyyy-MM-dd HH:mm:ss.SSSSSS XXX", TimeZone.getTimeZone("UTC"), Locale.US));
Prints:
2022-05-17 08:51:58.123456 00:00

**Expected behavior**
Should print:
2022-05-17 08:51:58.123456 +00:00

**Comment by kausandr** [comment]
Fidex in 530aa9fd3555d801ff8cc4c61a4e5530f3a26ec3.
