### ISSUE TITLE
Potential for ConcurrentModificationException with BufferedSink

### ISSUE THREAD

**Issue by jbnas** [Nastel/TNT4J#8]
When using BufferedSink, it appears that the log call is being processed by a thread other then the calling thread, which leads to a chance that the object involved in the log call is being concurrently accessed by multiple threads.  If the object's toString method involves iterating through a Collection, then it's possible for a ConcurrentModificationException.

Seems like the correct solution is for the string to be generated in the log call itself, so that it's done in the thread making the log call (or course after checking all necessary log levels and tokens), and it would be the string representation of the object that is being "buffered" for later writing to sink.

**Comment by amavashev** [comment]
Modified BufferedEventSink implementation to check for isLoggable() and resolve arguments if a given event is loggable to avoid toString() resolution in a different thread which may cause exceptions on some objects (such as SQL, maps, lists, etc).
